### ISSUE TITLE
会出现infra/conf/serial:failed to read config file at line 11 char>json: cannot unmarshal

### ISSUE THREAD

**Issue by ago23901248** [XTLS/AnXray#1]
**Describe the bug**
从N或者NG客户端导出配置（VLess）开始可以打开开关，进行一些设置后再开开关会出现失败：infra/conf/serial:failed to read config file at line 11 char>json: cannot unmarshal的toast提示

**To Reproduce**
1. 导入配置，此时可以成功开启代理
2. 打开分应用代理，打开安全建议，打开直连速度，开启默认路由开关（我一般的设置操作）
3. 再次打开代理开关

**Logcat**
Export it yourself :)

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. MI6]
 - OS: [e.g. Android8.1]
 - Version [e.g. 5.15.0]

**Additional context**

**Comment by ago23901248** [comment]
我的，我的，开了fake dns模式导致的，还不太会用，我再看看。
06-17 10:49:21.863  7650  7650 W BaseService$Interface$onStartCommand$2: go.Universe$proxyerror: infra/conf/serial: failed to read config file at line 11 char 14 > json: cannot unmarshal array into Go struct field Config.fakeDns of type conf.FakeDNSConfig
06-17 10:49:21.863  7650  7650 W BaseService$Interface$onStartCommand$2: 	at libv2ray.Libv2ray.testConfig(Native Method)
06-17 10:49:21.863  7650  7650 W BaseService$Interface$onStartCommand$2: 	at io.nekohasekai.sagernet.bg.ProxyInstance.init(Unknown Source:122)
06-17 10:49:21.863  7650  7650 W BaseService$Interface$onStartCommand$2: 	at io.nekohasekai.sagernet.bg.BaseService$Interface$onStartCommand$2.invokeSuspend(Unknown Source:55)
06-17 10:49:21.863  7650  7650 W BaseService$Interface$onStartCommand$2: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:2)
06-17 10:49:21.863  7650  7650 W BaseService$Interface$onStartCommand$2: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:86)
06-17 10:49:21.863  7650  7650 W BaseService$Interface$onStartCommand$2: 	at android.os.Handler.handleCallback(Handler.java:938)
06-17 10:49:21.863  7650  7650 W BaseService$Interface$onStartCommand$2: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-17 10:49:21.863  7650  7650 W BaseService$Interface$onStartCommand$2: 	at android.os.Looper.loop(Looper.java:246)
06-17 10:49:21.863  7650  7650 W BaseService$Interface$onStartCommand$2: 	at android.app.ActivityThread.main(ActivityThread.java:8512)
06-17 10:49:21.863  7650  7650 W BaseService$Interface$onStartCommand$2: 	at java.lang.reflect.Method.invoke(Native Method)
06-17 10:49:21.863  7650  7650 W BaseService$Interface$onStartCommand$2: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
06-17 10:49:21.863  7650  7650 W BaseService$Interface$onStartCommand$2: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by nekohasekai** [comment]
Xray 的 FakeDNS 还未支持 IPv6 导致的, 下个版本修复.
