### ISSUE TITLE
建议增加固定的UA头请求订阅更新

### ISSUE THREAD

**Issue by WayChan** [XTLS/AnXray#22]
目前如果协议选择 GRPC 配置，使用之前的 v2ray json字符串来分享地址，serviceName不会自动对应上json当中的path字段。
由于标准的vmess aead/vless分享链接其他平台支持度暂缺，同时目前使用的UA头为常规的okhttp，较多软件使用，建议软件请求订阅的时候可以使用固定的一个UA头，比如 "AnXray/version"，以便可以针对该软件进行自定义订阅适配。

**Comment by Funny-T** [comment]
https://github.com/XTLS/Xray-core/issues/91
这是标准的vmess aead/vless分享链接，
如果你使用的是vmess，据我所知，v2rayng仍使用自有分享链接而非官方的标准提案。
serviceName不对应path字段

4.3.11 (gRPC) serviceName

对应 gRPC 的 ServiceName。建议仅使用英文字母数字和英文句号、下划线组成。

不建议省略，不可为空字符串。

**Comment by WayChan** [comment]
> [XTLS/Xray-core#91](https://github.com/XTLS/Xray-core/issues/91)
> 这是标准的vmess aead/vless分享链接，
> 如果你使用的是vmess，据我所知，v2rayng仍使用自有分享链接而非官方的标准提案。
> serviceName不对应path字段
> 
> 4.3.11 (gRPC) serviceName
> 
> 对应 gRPC 的 ServiceName。建议仅使用英文字母数字和英文句号、下划线组成。
> 
> 不建议省略，不可为空字符串。

感谢解答，看了AnXray没有自定义UA头，使用的是okhttp，所以想对他进行自定义适配怕会有其他的影响。
目前使用编码字符串为
{
            "v" => "2",
            "ps" => "",
            "add" => "",
            "port" => "",
            "id" => "",
            "aid" => "",
            "net" => "",
            "type" => "none",
            "host" => "",
            "path" => "",
            "tls" => “”,
            "sni" => 
}
我将会尝试使用标准的vmess aead/vless分享链接来验证其他的客户端的兼容性，取一个合适自己的方式。
