### ISSUE TITLE
订阅中tls的值解析错误

### ISSUE THREAD

**Issue by zhangsan946** [XTLS/AnXray#35]
订阅中“tls”的值设置为“none”，然而生成的节点的“传输层加密”值仍然被设置为“tls”。
{
"v" => "2",
"ps" => "",
"add" => "",
"port" => "",
"id" => "",
"aid" => "",
"net" => "",
"type" => "",
"host" => "",
"path" => "",
"tls" => “none”,
"sni" =>
}

**Comment by nekohasekai** [comment]
Should be fixed
