### ISSUE TITLE
rc3 crash on Samsung Galaxy S21U when connection initialization

### ISSUE THREAD

**Issue by galaxyskyknight** [XTLS/AnXray#37]
try connection to node, disconnect immediately, try multiple times, crash.

**Comment by galaxyskyknight** [comment]
same node, same configuration, not happend on RC2

**Comment by galaxyskyknight** [comment]
I see ya removed the RC3:) probabaly you are fixing that.

**Comment by INetbeep** [comment]
I also encountered the same problem. Now the rc3 has been removed.
