### ISSUE TITLE
分应用代理自动扫描后无法玩ingress

### ISSUE THREAD

**Issue by ago23901248** [XTLS/AnXray#4]
**Describe the bug**
分应用代理自动扫描后无法玩ingress游戏 怀疑是一些框架应用gms之类的没被代理到或者是什么的
或者是我开启了绕过局域网地址？

**To Reproduce**
1. 打开分应用代理
2. 自动扫描应用（是否开启系统应用都试过）
3. 重新开启代理配置
4. 打开ingress会提示需要安全登录

**Logcat**
Export it yourself :)

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung s10
 - OS: Android 11
 - Version 

**Additional context**

**Comment by nekohasekai** [comment]
文档说了选中系统应用才会扫描系统的，不选就用绕过模式咯。
