### ISSUE TITLE
DNS over TCP not working

### ISSUE THREAD

**Issue by maskedeken** [XTLS/AnXray#8]
**Describe the bug**
DNS over TCP无效

**To Reproduce**
在本地DNS中指定tcp://1.1.1.1，服务端报如下错误：

2021/06/22 02:17:38 [Info] [109683213] app/proxyman/inbound: connection ends > proxy/trojan: failed to create request from: 127.0.0.1:35510 > proxy/trojan: failed to read address and port > common/protocol: invalid domain name: tcp://1.1.1.1

**Logcat**
Export it yourself :)

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. MI6]
 - OS: [e.g. Android8.1]
 - Version [e.g. 5.15.0]

**Additional context**
另：DNS配置不支持指定非53端口

**Comment by nekohasekai** [comment]
TCP DNS 是 v2fly/v2ray-core 的最新功能，请等 Xray 更新。
